const ActionTypes = {
  FETCH_SERVICES_LIST: 'FETCH_SERVICES_LIST',
  REMOVE_SERVICE: 'REMOVE_SERVICE',
  UPDATE_SERVICE_INFO: 'UPDATE_SERVICE_INFO',
  CREATE_SERVICE: 'CREATE_SERVICE',
  FETCH_MY_SERVICE_RECORDS: 'FETCH_MY_SERVICE_RECORDS',
  GET_MECHANIC_SCHEDULE: 'GET_MECHANIC_SCHEDULE',
  CHANGE_SERVICE_STATE: 'CHANGE_SERVICE_STATE'
}

export default ActionTypes
