const MutationTypes = {
  SET_SERVICES_LIST: 'SET_SERVICES_LIST',
  INDEXING_SERVICES_LIST: 'INDEXING_SERVICES_LIST',
  SET_MY_SERVICE_RECORDS_LIST: 'SET_MY_SERVICE_RECORDS_LIST'
}

export default MutationTypes
