const ActionTypes = {
  FETCH_SHOPPING_CART: 'FETCH_SHOPPING_CART',
  ADD_PRODUCT_TO_SHOPPING_CART: 'ADD_PRODUCT_TO_SHOPPING_CART',
  REMOVE_PRODUCT_FROM_SHOPPING_CART: 'REMOVE_PRODUCT_FROM_SHOPPING_CART'
}

export default ActionTypes
