const ActionTypes = {
  CREATE_ORDER: 'CREATE_ORDER',
  GET_ORDERS_LIST: 'GET_ORDERS_LIST',
  GET_ALL_ORDERS: 'GET_ALL_ORDERS',
  ACCEPT_ORDER: 'ACCEPT_ORDER',
  REJECT_ORDER: 'REJECT_ORDER',
  FINISH_ORDER: 'FINISH_ORDER'
}

export default ActionTypes
