const ActionTypes = {
  FETCH_PRODUCTS_LIST: 'FETCH_PRODUCTS_LIST',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT'
}

export default ActionTypes
