const ActionTypes = {
  GET_USERS_LIST: 'GET_USERS_LIST',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  FETCH_MECHANICS_LIST: 'FETCH_MECHANICS_LIST',
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  GET_CURRENT_USER_INFO: 'GET_CURRENT_USER_INFO',
  SAVE_NEW_USER_PASSWORD: 'SAVE_NEW_USER_PASSWORD'
}

export default ActionTypes
