const ActionTypes = {
  GET_USERS_LIST: 'GET_USERS_LIST',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  FETCH_MECHANICS_LIST: 'FETCH_MECHANICS_LIST'
}

export default ActionTypes
